//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syngenta.AIRIM.Hypothesis.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HypothesisEntities : DbContext
    {
        public HypothesisEntities()
            : base("name=HypothesisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<PROJECT_CODES_Result> APR_PROJECT_HYPOTHESIS_K_GET_PROJECT_CODES_P()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROJECT_CODES_Result>("APR_PROJECT_HYPOTHESIS_K_GET_PROJECT_CODES_P");
        }
    
        public virtual ObjectResult<APR_PROJECT_HYPOTHESIS_K_GET_PROJECT_DETAILS_P_Result> APR_PROJECT_HYPOTHESIS_K_GET_PROJECT_DETAILS_P(string cODE)
        {
            var cODEParameter = cODE != null ?
                new ObjectParameter("CODE", cODE) :
                new ObjectParameter("CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<APR_PROJECT_HYPOTHESIS_K_GET_PROJECT_DETAILS_P_Result>("APR_PROJECT_HYPOTHESIS_K_GET_PROJECT_DETAILS_P", cODEParameter);
        }
    }
}
